# config/api_keys.py

# Your OpenRouteService API key
OPENROUTESERVICE_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6Ijg3YTI4ODI2YTc0OTRjODNiM2JkYTYzMDYxMGQxMWRjIiwiaCI6Im11cm11cjY0In0="
